---
version: '3.9'


services:
  emqx_server:
    container_name: emqx
    image: emqx/emqx:5.0.9
    network_mode: host

  prometheus:
    container_name: prometheus
    image: quay.io/prometheus/prometheus:v2.39.1
    network_mode: host
    command:
    - '--web.enable-remote-write-receiver'
    - '--config.file=/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
    - ${PWD}/data/prometheus.yml:/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:9.0.5
    network_mode: host

  # alertmanager:
  #   image: quay.io/prometheus/alertmanager:v0.24.0
  #   container_name: alertmanager
  #   network_mode: host

  # discord-alert:
  #   image: benjojo/alertmanager-discord:latest
  #   container_name: discord-alert
  #   environment:
  #     DISCORD_WEBHOOK: ${DISCORD_WEBHOOK}
  #   network_mode: host
...
