{
 "title": "iot-sensors",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Noore Daakhele Tanker",
   "type": "timeseries",
   "description": "nooori ke dakhele tanker vojud daare",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sensor_ldr" }
   ]
  },
  {
   "title": "hajme aabe taanker",
   "type": "timeseries",
   "description": "chand darsad az kole tanker poor shode\n",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "100 - sensor_us" }
   ]
  },
  {
   "title": "Hajme felie aab",
   "type": "gauge",
   "description": "chand darsad az taanker por ast",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "100 - sensor_us" }
   ]
  },
  {
   "title": "Damaaye tanker",
   "type": "timeseries",
   "description": "daamaye daakhele tanker",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "sensor_ds" }
   ]
  },
  {
   "title": "damaaye felie tanker",
   "type": "gauge",
   "description": "aakharin damayi ke az tanker daryaft shode",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sensor_ds" }
   ]
  }
 ]
}